services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    image: omerteomim/api_app:latest
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
  pgdata: