name: Build and Push Docker Image

on:
  push:
    branches:
      - main  
jobs:
  build-and-push-to-dockerhub:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Docker image tag
        id: vars
        run: |
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          echo "IMAGE_TAG=v${TIMESTAMP}" >> $GITHUB_OUTPUT

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and tag Docker images
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/pokemon_app:${{ steps.vars.outputs.IMAGE_TAG }} .
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/pokemon_app:${{ steps.vars.outputs.IMAGE_TAG }} ${{ secrets.DOCKERHUB_USERNAME }}/pokemon_app:latest
          docker images

      - name: Push Docker images to Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/pokemon_app:${{ steps.vars.outputs.IMAGE_TAG }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/pokemon_app:latest